7.2.1 wiedergabe von audiodeskription
BIK-BITV/BIK-Web-Test pull request #103
Opened 2021-01-25 16:24 UTC by sweckenmann

2021-01-25 16:46 UTC, detlevhfischer commented
Ich würde noch deutlicher machen, dass im Idealfall AD nicht notwendig ist, wenn nämlich alle wichtigen informationstragenden Bildinhalte ohnehin auch im Ton vorkommen - vielleicht auch zu ausführlich.

> Werden Inhalte eines Videos nur visuell vermittelt, sind Beschreibungen der informationstragenden Inhalte 
für blinde Menschen notwendig. Nur dann ist das Video für sie verständlich. Im besten Fall sind im Video alle wichtigen visuell informationstragenden Elemente auch im Ton verfügbar. Dazu gehören zum Beispiel Namen von Sprechern oder Interviewpartnern, die im Bild als Text eingeblendet werden. In anderen Fällen kann dafür 
das Verfahren der Audiodeskription eingesetzt werden um solche Inhalte zusätzlich in Lücken der Tonspur zu beschreiben.

2021-01-25 16:48 UTC, detlevhfischer commented on Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
> +Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen
Siehe Kommentar unter Reiter Conversation

2021-01-25 16:49 UTC, detlevhfischer requested changes
Siehe mein Kommentar unter Reiter Conversation (hab das noch nicht raus, wie das mit dieser Review Finktion funktionniert..)

2021-01-25 17:19 UTC, sweckenmann commented on Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
> +Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen
Das würde ich hier nicht so ausführlich behandeln. Hier wird nur geprüft, ob ein Bedienelement da, ist mit dem man AD starten kann. Ob AD nötig ist oder ob man es vermeiden kann etc. gehört zum WCAG Prüfschritt 1.2.5 (weiß grad die EN-Nummer nicht auswendig). Siehe Abgrenzung des Prüfschritts. Evtl. kann man bei 1.2.5 ausführlicher beschreiben, dass AD optimalerweise nicht notwendig ist.

2021-01-25 17:22 UTC, detlevhfischer commented on Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
> +Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen
Ja, einverstanden. Dann vielleicht noch knapper: Wenn AD angeboten wird, ist das für Menschen die das brauchen wichtig und deswegen soll es auf gleicher Ebene stehen

2021-01-25 17:26 UTC, sweckenmann commented on Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
> +Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen
Dass der AD-Knopf auf der obersten Ebene positioniert sein soll, wird bei 7.3 geprüft. Nicht in diesem Prüfschritt. Nicht vermischen.
Unter Abgrenzung steht, wenn 7.3 erfüllt ist, ist auch 7.2.1 erfüllt.

2021-01-25 17:27 UTC, detlevhfischer commented on Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
> +Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen
Z.B.: "Wenn visuelle Inhalte eines Videos über eine zusätzliche Audiodeskription angeboten werden, muss der eingesetzte Player ein Bedienelement haben, mit dem die zusätzliche Audiodeskription eingeblendet werden kann" o.ä.

2021-01-25 17:27 UTC, sweckenmann commented on Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
> +Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen
äh... bei Hinweise steht das.

2021-01-25 17:29 UTC, sweckenmann commented on Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
> +Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen
ok

2021-01-25 17:39 UTC, sweckenmann commented on Prüfschritte/de/7.2.1 Wiedergabe von Audiodeskription.adoc
> +Werden Inhalte eines Videos nur über Bilder vermittelt, sind Beschreibungen der Bildsequenzen
Wobei: Steht doch aber schon im zweiten Absatz:

> Damit Nutzende Audiodeskription ein- und ausschalten können, muss der eingesetzte Player ein 
> entsprechendes AD-Bedienelement oder die Möglichkeit, eine Tonspur mit Audiodeskription in den 
> Spracheinstellungen zu aktivieren, anbieten.

Du kannst das auch durch deine Formulierung ersetzen, oder willst du den ersten Absatz von "Warum wird das geprüft" kürzen?

2021-02-09 09:43 UTC, sweckenmann reviewed
ok

2021-02-10 13:37 UTC, merged