12.1.1 Selbsterklärende Funktionen
BIK-BITV/BIK-Web-Test pull request #152
Opened 2021-02-25 10:21 UTC by sweckenmann

* Anwendbarkeit: Zusatz eingefügt "anwendbar, wenn Dokumentation vorhanden"
* Prüfung: Beispiele Kontrastumschalter / Schalter für Farbschemata / , Vergrößerungsfunktion, Deaktivierung von Bewegungen oder automatischen Audios, Verzeichnisse für Abkürzungen entfernt
* Hinweise: Zusatz: Selbsterklärende Funktionen wie Kontrastschalter, Vergrößerungsschalter.. sollten nicht negativ bewertet werden

2021-02-25 10:26 UTC, sweckenmann commented
@detlevhfischer - Ist es so, dass der Prüfschritt nur anwendbar ist, wenn eine Dokumentation vorhanden? Oder müssen die Funktionen immer erklärt werden?

2021-02-25 11:12 UTC, johannesFischer84 commented
> @detlevhfischer - Ist es so, dass der Prüfschritt nur anwendbar ist, wenn eine Dokumentation vorhanden? Oder müssen die Funktionen immer erklärt werden?

Ich bin zwar nicht gefragt, antworte aber trotzdem mal. Ja, der Prüfschritt sollte nur anwendbar sein, wenn Dokumentation vorhanden ist. Das ist aber bereits gegeben, wenn eine Erklärung zur Barrierefreiheit vorhanden ist. Siehe in der EN den Anhang C, C.12.1.1 und dort die Precondition: "Product documentation is supplied with the ICT."
Laut Kapitel 14, 2. Absatz in der EN geben die Preconditions immer an, ob eine Prüfung anwendbar ist oder nicht.

2021-03-03 10:21 UTC, detlevhfischer requested changes
Siehe Kommentare...

2021-03-03 10:21 UTC, detlevhfischer commented on Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc
> +. Nicht negativ bewertet werden sollen sehr übliche und selberklärende Funktionen wie Kontrastschalter, Schalter für Farbschemata, Vergrößerungsfunktionen, Schalter für die Deaktivierung von Bewegung
9.2.4.6 verlangt ja aber nicht, dass die oft eingesetzten Icons für Kontrast, Textgröße usw. eine textuelle beschriftung haben. Nir das Beschriftungen, wenn vorhanden, aussagekräftig sind.

2021-03-03 10:21 UTC, detlevhfischer commented on Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc
> +** Aktivierung verbesserter Darstellungen des Maus- oder Tastaturfokus
Vielleicht kann man hier sagen "Funktionen die Nutzern die einstellung individueller Farbschemata erlauben"? Das würde den simplen Kontrastumschalter ausschließen.

2021-03-03 10:21 UTC, detlevhfischer commented on Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc
> +Die Dokumentation des Webangebots soll vorhandene zusätzliche Eigenschaften und Funktionen in Bezug auf Barrierefreiheit auflisten und deren Nutzung erklären, sofern diese als Teil des Web-Angebots s
Dazu gehören zum Beispiel Vorlesefunktionen, Funktionen zum Einstellen individueller Farbschemata oder verfügbare Tastaturkurzbefehle.

2021-03-03 13:35 UTC, detlevhfischer requested changes
Siehe Kommentare  unten.

2021-03-03 17:27 UTC, sweckenmann commented on Prüfschritte/de/12.1.1 Dokumentation von Kompatibilität und Barrierefreiheit.adoc
> +** Aktivierung verbesserter Darstellungen des Maus- oder Tastaturfokus
Hab deinen Vorschlag übernommen. Vergrößerungsfunktion und Deaktivierung von Bewegungen oder automatischen Audios sowie Verzeichnisse für Abkürzungen hatte ich auch rausgenomme???

2021-03-29 12:57 UTC, merged