7.1.5 spoken subtitles
BIK-BITV/BIK-Web-Test pull request #246
Opened 2022-02-03 14:40 UTC by sweckenmann

- Prüfschrittname geändert
- Anwendbar, wenn fremdsprachige Untertitel vorhanden sind.
- Warum wird das geprüft: Angepasst.
- FRAGE: Soll der Satz bei "Warum wird das geprüft "Sie können zum Beispiel als zusätzliche Tonspur oder über eine Text-to-Speech Funktionalität bereitgestellt werden." besser raus? Keinen Hinweis zur Umsetzung? Gibt es eine technisch bessere Formulierung?

2022-02-03 15:00 UTC, mtelgkamp commented
Woher kommt die Limitierung auf **fremdsprachige** Untertitel?

Ist der Prüfschritt also erfüllt, wenn man keine fremdsprachigen Untertitel anbietet, aber wenn man zusätzliche Informationen anbietet ist der Prüfschritt nicht mehr bestanden?

Wie bei "3. Hinweise" geschrieben, gibt es auch nach meinem Wissen aktuell keine technische Möglichkeit den Prüfschritt zu erfüllen. Der Prüfschritt ist also, wenn er wie in diesem Pull Request beschrieben ausgelegt wird, ein (indirektes) Verbot von programmatisch ermittelbaren fremdsprachigen Untertiteln.

Siehe auch Diskussion in #241

2022-02-03 16:23 UTC, sweckenmann commented
Anwendbarkeit gändert (nur bei fremdsprachigen Videos mit zusätzlich angebotenen UT in der Hauptsprache der Seite).
Evtl. könnte man auch sagen, wenn es eine Tonspur in der Hauptsprache der Seite gibt, ist der Prüfschritt "erfüllt" (statt "nicht anwendbar"?) - das wär ja eine Synchronisation.

2022-02-06 19:24 UTC, johannesFischer84 commented
> Da sich auch bei uns Fragen ergeben haben (und aufgrund der Diskussion https://github.com/BIK-BITV/BIK-Web-Test/issues/241) haben wir versucht, detailiertere Informationen zu bekommen und uns an eine Person des Normungsgremiums (das heißt, die an der Weiterentwicklung der EN mitarbeitet), gewandt. Aus deren Rückmeldung entnehmen wir, dass die Anforderung darin begründet ist, blinden und sehbehinderten Menschen fremdsprachige Untertitel zugänglich zu machen (siehe "Warum wird das geprüft").

Sonja, ich hatte mich auch schon gefragt, was ihr jetzt mit Fremdsprachen in diesem Kriterium wollt. Toll, dass ihr nähere Infos zu dem Kriterium von den Leuten erhalten habt, die an der EN arbeiten. Man kann das mit der Aussprache der Fremdsprache ggf. in das Kriterium hineininterpretieren, aber es steht überhaupt nicht klar drin (leider). Damit nicht häufiger solche Fragen gestellt werden, warum das mit der Fremdsprache in der Prüfanleitung steht, nicht aber im EN-Kriterium, sollte man besser irgendwo in der Anleitung (z. B. unter Hinweise), dass diese Information aus dem Normungsgremium der EN erfragt wurde.

> FRAGE: Soll der Satz bei "Warum wird das geprüft "Sie können zum Beispiel als zusätzliche Tonspur oder über eine Text-to-Speech Funktionalität bereitgestellt werden." besser raus? Keinen Hinweis zur Umsetzung? Gibt es eine technisch bessere Formulierung?

Ich finde den Satz gut so.

2022-02-07 08:18 UTC, sweckenmann commented
@johannesFischer84 Danke für deine Rückmeldung. Ja, lediglich aufgrund der Verwendung der Begriffe "subtitles" könnte man darauf kommen, dass eben nicht die "normalen" captions gemeint sind, sondern eben die übersetzten Untertitel. Der Begriff wird jedoch nicht ganz konsistent durchgehalten. Aber du hast recht, es könnte wirklich zu Irritationen kommen. Vielleicht sollte man da wirklich was in den Prüfschritt schreiben.

2022-02-07 14:15 UTC, detlevhfischer requested changes
Siehe Anmerkungen unten...

2022-02-07 14:15 UTC, detlevhfischer commented on Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
> +* Bei zuschaltbaren, programmatisch ermittelbaren fremdsprachigen Untertiteln gibt es keine Möglichkeit, eine Sprachausgabe der Untertitel zu aktivieren.
Nein. Es müsste etwa heißen: "Bei Angeboten mit fremdsprachiger Tonspur und Untertiteln in der Hauptsprache gibt es keine Möglichkeit, eine Sprachausgabe dieser Untertitel zu aktivieren."
Ggf. muss man noch den Fall berücksichtigen, dass sich bei einem Video mit fremdsprachiger Tonspur und hauptsprachigne Untertiteln auch eine Version mit hauptsprachiger Tonspur aufrufen lässt. Dann müssten eine Ausgabe der hauptsprachigen Untertitel nicht aktivierbar sein.

2022-02-07 14:17 UTC, detlevhfischer commented on Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
> +* und Unteritel in der Hauptsprache des Webauftritts bereitgestellt werden.
Ergänzen: ...und keine Version des Videos mit hauptsprachiger Tonspur zur Verfügung steht.

2022-02-07 14:19 UTC, detlevhfischer requested changes

2022-02-07 14:19 UTC, detlevhfischer commented on Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
> +. Prüfen ob neben der Originalsprache Untertitel in der Hauptsprache des Webangebots angeboten werden.
Schritt 2: Prüfen, ob für Videos mit fremdsprachiger Tonspur Untertitel in der Hauptsprache des Webangebots angeboten werden.

2022-02-10 17:13 UTC, detlevhfischer commented on Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
> +Wenn das Webangebot Videos mit einem Orginalton enthält, der nicht der Hauptsprache des Webangebots entspricht, sollen zuschaltbaren bzw. programmatisch ermittelbaren Untertitel, die in der Hauptspra
..als akustische Ausgabe zugänglich sein, z.B. über eine eigene Tonspur, die den Untertiteln entspricht, oder über eine gnerierte Sprachausgabe der Untertitel.

2022-02-10 17:16 UTC, detlevhfischer commented on Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
> +Menschen, die fremdsprachigen Originalton eines Videos nicht verstehen, profitieren von Untertiteln in ihrer Landessprache. Wenn Untertitel in der Hauptsprache des Webangebots angeboten werden, solle
Für Menschen, die den fremdsprachigen Originalton eines Videos nicht verstehen, ist eine Übersetzung in Untertiteln in der eigenen Sprache wichtig. Diese Untertitel sollen auch für blinde oder seheingeschränkte Menschen als akustische Ausgabe zugänglich sein.

2022-02-10 17:18 UTC, detlevhfischer commented on Prüfschritte/de/7.1.5 Gesprochene Untertitel.adoc
> +. Falls es sich dabei um zuschaltbare bzw. programmatisch ermittelbare Untertitel handelt: Prüfen, ob sich eine Sprachausgabe der Untertitel aktivieren lässt.
Prüfen, ob sich eine alternative Tonspur in der Hauptsprache des Angebots oder eine generierte Sprachausgabe der Untertitel aktivieren lässt.

2022-02-10 17:18 UTC, detlevhfischer requested changes
Siehe Vorschläge in den Kommentaren.

2022-02-10 17:20 UTC, sweckenmann commented
Deine letzten Änderungswunsch gerade eingepflegt, die anderen müssten auch drin sein, schau mal, ob einverstanden. Sonst kannst du selbst editieren, wenn du willst.

2022-02-10 17:20 UTC, sweckenmann commented
Ah, moment, noch nicht alles drin.

2022-02-10 17:26 UTC, sweckenmann commented
Müsste so okay sein?

2022-02-11 17:33 UTC, merged

2022-02-21 20:12 UTC, johannesFischer84 commented
Ich bin in der EN 301 549 und einer verknüpften Norm noch auf etwas zu dem Thema gestoßen, was u. a. das mit der Fremdsprache belegen würde:

Im Abschnitt 3 der EN (Definitionen) gibt es folgende Begriffsdefinition: "**spoken captions/subtitles audio captions/subtitles**: captions/subtitles that are voiced over the audiovisual content (from ISO/IEC TS 20071-25 [i.31])"

Das ist die passende Definition für die Begrifflichkeit in EN 7.1.5. Die [in der Definition genannte Norm](https://www.iso.org/standard/69060.html) beschäftigt sich laut Beschreibung mit der auditiven Darstellung von Text aus Videos (inkl. Untertiteln). Wörtlich heißt es in der Beschreibung:

> ISO/IEC TS 20071-25:2017 applies to making captions/subtitles and other on-screen text accessible to users with various needs, including but not limited to people with learning and reading disabilities, people with cognitive disabilities, people who are blind or have low vision, older people, and non-native language speakers. It does not apply to captions/subtitles or other on-screen text whose content is already provided in the soundtrack in a language and a way users can access.

Entsprechend dem letzten Satz ist die Norm (und damit wohl das Kriterium 7.1.5) nicht anwendbar, wenn der Text in einer Sprache vorliegt, welche die Nutzer verwenden können (also wohl die gleiche Sprache wie die Untertitel) und wenn der Inhalt der Untertitel in der Audiospur des Videos so vorliegt, dass Nutzer sie wahrnehmen können.

Folglich ist 7.1.5 anwendbar, wenn die Untertitel in einer anderen Sprache verfasst sind als die Tonspur des Videos (schon in unserer Anleitung vorhanden) oder wenn die Sprache in der Tonspur schwer verständlich ist (noch nicht enthalten). Letzteres ist der Fall, wenn schwer verständlicher Dialekt gesprochen wird - z. B. ist schweizer / liechtensteiner Dialekt für Deutsche oft nicht leicht verständlich - oder wenn genuschelt wird bzw. die Tonqualität schlecht ist. In diesem Fall werden in Videos meist auch Untertitel eingeblendet, um die Verständlichkeit zu erhöhen. Diese Untertitel müssen dann auch in verständlicher Form auditiv ausgebbar sein (sofern programmatisch ermittelbar und nicht nur ins Bild eingebrannt).

Vielleicht könnte zum einen das mit den Dialekten bzw. schwerer Verständlichkeit noch in die Anleitung integriert werden. Ebenso könnte man in den Quellen auf die Definition aus Abschnitt 3 der EN und die verlinkte ISO-Norm verweisen.